/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import config.DatabaseConnection; // sesuaikan jika nama kamu beda



/**
 *
 * @author Asus
 */
public class SiswaForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SiswaForm.class.getName());

    /**
     * Creates new form SiswaForm
     */
    public SiswaForm() {
        initComponents();
        isiComboKelas();
        isiComboJurusan();
        tampilDataSiswa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNis = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        lblJK = new javax.swing.JLabel();
        cbJenisKelamin = new javax.swing.JComboBox<>();
        lblTgl = new javax.swing.JLabel();
        lblJK1 = new javax.swing.JLabel();
        cbKelas = new javax.swing.JComboBox<>();
        lblJurusan = new javax.swing.JLabel();
        cbJurusan = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();
        txtTanggalLahir = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA SISWA");

        txtNis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNisActionPerformed(evt);
            }
        });

        jLabel2.setText("NIS :");

        lblName.setText("Nama Siswa :");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        lblJK.setText("Jenis Kelamin :");

        cbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "L", "P", " " }));
        cbJenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisKelaminActionPerformed(evt);
            }
        });

        lblTgl.setText("Tanggal Lahir :");

        lblJK1.setText("Kelas :");

        lblJurusan.setText("Jurusan");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSiswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblJK, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtNis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTambah))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnEdit))))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblJK1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(273, 273, 273)
                                    .addComponent(btnReset))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(105, 105, 105)
                                    .addComponent(btnHapus))))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lblName)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJK)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTgl)
                        .addComponent(btnEdit))
                    .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJK1)
                            .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblJurusan)
                        .addComponent(cbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHapus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isiComboKelas() {
        try {
            Connection conn = DatabaseConnection.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT nama_kelas FROM kelas");
            while (rs.next()) {
                cbKelas.addItem(rs.getString("nama_kelas"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal isi kelas: " + e.getMessage());
        }
    }

    private void isiComboJurusan() {
        try {
            Connection conn = DatabaseConnection.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT nama_jurusan FROM jurusan");
            while (rs.next()) {
                cbJurusan.addItem(rs.getString("nama_jurusan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal isi jurusan: " + e.getMessage());
        }
    }

    private void tampilDataSiswa() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIS");
        model.addColumn("Nama");
        model.addColumn("JK");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Kelas");
        model.addColumn("Jurusan");

        try {
            String sql = "SELECT siswa.nis, nama_siswa, jenis_kelamin, tanggal_lahir, kelas.nama_kelas, jurusan.nama_jurusan " +
                         "FROM siswa " +
                         "JOIN kelas ON siswa.id_kelas = kelas.id " +
                         "JOIN jurusan ON siswa.id_jurusan = jurusan.id";

            Connection conn = DatabaseConnection.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nis"),
                    rs.getString("nama_siswa"),
                    rs.getString("jenis_kelamin"),
                    rs.getDate("tanggal_lahir"),
                    rs.getString("nama_kelas"),
                    rs.getString("nama_jurusan")
                });
            }

            tableSiswa.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal tampil data: " + e.getMessage());
        }
    }
    
    private int getIdKelas(String nama) throws SQLException {
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pst = conn.prepareStatement("SELECT id FROM kelas WHERE nama_kelas=?");
        pst.setString(1, nama);
        ResultSet rs = pst.executeQuery();
        if (rs.next()) return rs.getInt("id");
        return 0;
    }

    private int getIdJurusan(String nama) throws SQLException {
        Connection conn = DatabaseConnection.getConnection();
        PreparedStatement pst = conn.prepareStatement("SELECT id FROM jurusan WHERE nama_jurusan=?");
        pst.setString(1, nama);
        ResultSet rs = pst.executeQuery();
        if (rs.next()) return rs.getInt("id");
        return 0;
    }


    private void txtNisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNisActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed
    
    private String getKodeJenisKelamin() {
        String selected = cbJenisKelamin.getSelectedItem().toString();
        return selected.equals("Laki-laki") ? "L" : "P";
    }
    private void cbJenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisKelaminActionPerformed
        
    }//GEN-LAST:event_cbJenisKelaminActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            Connection conn = DatabaseConnection.getConnection();
            String sql = "UPDATE siswa SET nama_siswa=?, jenis_kelamin=?, tanggal_lahir=?, id_kelas=?, id_jurusan=? WHERE nis=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtNama.getText());
            pst.setString(2, cbJenisKelamin.getSelectedItem().toString());
            pst.setDate(3, java.sql.Date.valueOf(txtTanggalLahir.getText()));
            pst.setInt(4, getIdKelas(cbKelas.getSelectedItem().toString()));
            pst.setInt(5, getIdJurusan(cbJurusan.getSelectedItem().toString()));
            pst.setString(6, txtNis.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diedit");
            tampilDataSiswa();
            resetForm();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal edit data: " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
        Connection conn = DatabaseConnection.getConnection();
        String sql = "DELETE FROM siswa WHERE nis=?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txtNis.getText());
        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        tampilDataSiswa();
        resetForm();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal hapus data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
        Connection conn = DatabaseConnection.getConnection();
        String sql = "INSERT INTO siswa (nis, nama_siswa, jenis_kelamin, tanggal_lahir, id_kelas, id_jurusan) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, txtNis.getText());
        pst.setString(2, txtNama.getText());
        pst.setString(3, getKodeJenisKelamin());

        // ✅ Ambil tanggal dari JDateChooser
        java.util.Date utilDate = txtTanggalLahir.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        pst.setDate(4, sqlDate); // ✅ Gunakan ini saja

        pst.setInt(5, getIdKelas(cbKelas.getSelectedItem().toString()));
        pst.setInt(6, getIdJurusan(cbJurusan.getSelectedItem().toString()));
        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
        tampilDataSiswa();
        resetForm();

        } catch (Exception e) {
            e.printStackTrace(); // detail error muncul di console
            JOptionPane.showMessageDialog(null, "Gagal tambah data");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tableSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSiswaMouseClicked
        int row = tableSiswa.getSelectedRow();
        txtNis.setText(tableSiswa.getValueAt(row, 0).toString());
        txtNama.setText(tableSiswa.getValueAt(row, 1).toString());
        cbJenisKelamin.setSelectedItem(tableSiswa.getValueAt(row, 2).toString());
        txtTanggalLahir.setText(tableSiswa.getValueAt(row, 3).toString());
        cbKelas.setSelectedItem(tableSiswa.getValueAt(row, 4).toString());
        cbJurusan.setSelectedItem(tableSiswa.getValueAt(row, 5).toString());
        txtNis.setEditable(false);
    }//GEN-LAST:event_tableSiswaMouseClicked

    private void resetForm() {
        txtNis.setText("");
        txtNama.setText("");
        cbJenisKelamin.setSelectedIndex(0);
        txtTanggalLahir.setText("");
        cbKelas.setSelectedIndex(0);
        cbJurusan.setSelectedIndex(0);
        txtNis.setEditable(true);
    }
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SiswaForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbJenisKelamin;
    private javax.swing.JComboBox<String> cbJurusan;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJK;
    private javax.swing.JLabel lblJK1;
    private javax.swing.JLabel lblJurusan;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTgl;
    private javax.swing.JTable tableSiswa;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNis;
    private com.toedter.calendar.JDateChooser txtTanggalLahir;
    // End of variables declaration//GEN-END:variables
}
